# output/html_report.py

def generate_html(parsed_frame) -> str:
    """
    يولد تقرير HTML منسق وجميل يحتوي على تفاصيل الإطار.
    تم استخدام CSS مدمج لضمان عمل التقرير كملف واحد مستقل (Standalone).
    """
    html = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>80211Probe - Analysis Report</title>
        <style>
            body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 40px; background-color: #f4f6f9; color: #333; }}
            h1 {{ border-bottom: 2px solid #007bff; padding-bottom: 10px; color: #0056b3; }}
            .card {{ background: #fff; padding: 20px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); margin-bottom: 25px; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 10px; }}
            th, td {{ text-align: left; padding: 12px; border-bottom: 1px solid #e9ecef; }}
            th {{ background-color: #f8f9fa; color: #495057; width: 30%; }}
            tr:hover {{ background-color: #f1f3f5; }}
            .badge {{ background-color: #28a745; color: white; padding: 5px 10px; border-radius: 12px; font-size: 14px; font-weight: bold; }}
        </style>
    </head>
    <body>
        <h1>📡 80211Probe - Wireless Frame Analysis</h1>
        
        <div class="card">
            <h2>⚙️ Frame Control (MAC Header)</h2>
            <table>
                <tr><th>Type</th><td>{parsed_frame.frame_control.type}</td></tr>
                <tr><th>Subtype</th><td>{parsed_frame.frame_control.subtype}</td></tr>
                <tr><th>Protected Frame (Encrypted)</th><td>{parsed_frame.frame_control.protected_frame}</td></tr>
            </table>
        </div>

        <div class="card">
            <h2>📍 MAC Addresses</h2>
            <table>
                <tr><th>Receiver (Address 1)</th><td>{parsed_frame.addresses.addr1}</td></tr>
                <tr><th>Transmitter (Address 2)</th><td>{parsed_frame.addresses.addr2}</td></tr>
                <tr><th>BSSID (Address 3)</th><td>{parsed_frame.addresses.addr3}</td></tr>
            </table>
        </div>
    """
    
    if parsed_frame.elements:
        html += """
        <div class="card">
            <h2>📋 Information Elements (IEs)</h2>
            <table>
                <tr><th>Element ID</th><th>Length</th><th>Data / Value</th></tr>
        """
        for ie in parsed_frame.elements:
            if ie.id == 0:
                try:
                    data_str = f"<span class='badge'>SSID: {ie.data.decode('utf-8')}</span>"
                except UnicodeDecodeError:
                    data_str = ie.data.hex()
            else:
                data_str = ie.data.hex()
                
            html += f"<tr><td>{ie.id}</td><td>{ie.length} Bytes</td><td>{data_str}</td></tr>"
        html += "</table></div>"

    html += """
        <div style="text-align: center; margin-top: 50px; font-size: 14px; color: #6c757d;">
            Generated by 80211Probe - Cybersecurity Project
        </div>
    </body>
    </html>
    """
    return html